<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Price</name>
   <tag></tag>
   <elementGuidId>8a125e7e-fa11-4a5f-ad62-dae16539de40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/main[@id='root-app']/div/div/div/div/div/div/div/div/div/span/span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
